# Generated by Django 4.2.6 on 2023-10-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_alter_book_email'),
        ('core', '0006_alter_service_body'),
    ]

    operations = [
    ]
