# Generated by Django 4.2.6 on 2023-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_email'),
        ('core', '0007_merge_20231009_0656'),
    ]

    operations = [
    ]
