# Generated by Django 4.2.6 on 2023-10-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20231009_0700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
