# Generated by Django 4.2.3 on 2023-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_comment_remove_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
