# Generated by Django 4.2.6 on 2023-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='option',
            field=models.BooleanField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thurday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=True),
        ),
    ]
